VERSION: ${pom.version}
# Times at which the server shall restart
# Format: HH:mm
Restart Times:
    - "02:00"
    - "08:00"
    - "14:00"
    - "20:00"

# Time differences until restart to broadcast warning messages
# Format: HH:mm
Warning Times:
    - "00:15"
    - "00:10"
    - "00:05"
    - "00:03"
    - "00:02"
    - "00:01"

# Delay between last warning message and restart
# value is in seconds
Last Warning: 10
