VERSION: ${pom.version}
# Alle Zeiten im Format hh:mm angegben
Restart Times:
    - "18:00"
    - "23:59"
    - "10:15"

# Zeitdifferenz bis zum nächsten Restart
Warning Times:
    - "00:10"
    - "00:05"
    - "00:01"
