name: DieHard
main: de.minestar.diehard.core.DieHardCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
  restart:
    description: Restart the server
    usage: /restart <Time in minutes>