name: AutoRestart
main: de.minestar.autorestart.core.AutoRestartCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
  restart:
    description: Restart the server
    usage: /restart <Time in minutes>