name: DieHard
main: de.minestar.diehard.core.DieHardCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
  neustart:
    description: Restart the server
    usage: /neustart <Time in minutes>